# using REST Client extension for VS Code to build and test API requests from satnogs network
# link of extention: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
GET https://network.satnogs.org/api/observations/?norad_cat_id=51657

###
GET https://network.satnogs.org/api/observations/?cursor=cD0yMDI1LTExLTA4KzE2JTNBNDYlM0EyNyUyQjAwJTNBMDA%3D&norad_cat_id=51657

###
GET https://network.satnogs.org/api/observations/?cursor=cD0yMDIyLTA1LTEyKzEwJTNBMjUlM0EzNCUyQjAwJTNBMDA%3D&norad_cat_id=51657

###
GET  https://network.satnogs.org/api/observations/?cursor=cD0yMDI1LTAyLTIwKzE4JTNBMDglM0E1MiUyQjAwJTNBMDA%3D&norad_cat_id=51657